// Generated by CoffeeScript 1.4.0
var app, big_tree_tile, butterfly_tile, cat_veto_tile, child_tile, childhood, chute, chute_anar_tile, chute_bottle_tile, chute_coco_tile, chute_heart_tile, chute_hippie_tile, chute_me_tile, chute_sky_tile, chute_wall_tile, cosmos_tile, earth_tile, end, little_tree_tile, moon_tile, sky_tile, smoke_tile, spuf_tile, text, veto_tile,
  _this = this;

child_tile = {
  x: 12,
  y: 1,
  w: 50,
  h: 110,
  startX: 0,
  startY: 0,
  partW: 12 * 50,
  partH: 110
};

cosmos_tile = {
  x: 12,
  y: 1,
  w: 50,
  h: 110,
  startX: 0,
  startY: 111,
  partW: 12 * 50,
  partH: 110
};

veto_tile = {
  x: 6,
  y: 2,
  w: 71,
  h: 101,
  startX: 0,
  startY: 222,
  partW: 6 * 71,
  partH: 101
};

smoke_tile = {
  x: 6,
  y: 1,
  w: 50,
  h: 110,
  startX: 0,
  startY: 111,
  partW: 6 * 50,
  partH: 110
};

spuf_tile = {
  x: 3,
  y: 2,
  w: 120,
  h: 120,
  startX: 0,
  startY: 0,
  partW: 3 * 120,
  partH: 2 * 120
};

butterfly_tile = {
  x: 5,
  y: 1,
  w: 22,
  h: 27,
  startX: 0,
  startY: 5 * 111,
  partW: 5 * 22,
  partH: 27
};

earth_tile = {
  w: 800,
  h: 138,
  imgW: 400,
  imgH: 138,
  startX: 0,
  startY: 0
};

moon_tile = {
  w: 800,
  h: 138,
  imgW: 340,
  imgH: 138,
  startX: 0,
  startY: 0
};

sky_tile = {
  w: 800,
  h: 500,
  imgW: 375,
  imgH: 319,
  startX: 0,
  startY: 138
};

big_tree_tile = {
  w: 800,
  h: 326,
  imgW: 400,
  imgH: 326,
  startX: 500,
  startY: 0
};

little_tree_tile = {
  w: 800,
  h: 149,
  imgW: 400,
  imgH: 149,
  startX: 500,
  startY: 370
};

cat_veto_tile = {
  w: 800,
  h: 149,
  imgW: 399,
  imgH: 149,
  startX: 501,
  startY: 370
};

chute_sky_tile = {
  w: 800,
  h: 600,
  imgW: 598,
  imgH: 389,
  startX: 0,
  startY: 0
};

chute_wall_tile = {
  w: 78,
  h: 600,
  imgW: 78,
  imgH: 145,
  startX: 598,
  startY: 0
};

chute_me_tile = {
  x: 7,
  y: 1,
  w: 111,
  h: 132,
  startX: 0,
  startY: 389,
  partW: 7 * 111,
  partH: 133
};

chute_bottle_tile = {
  x: 1,
  y: 1,
  w: 24,
  h: 74,
  startX: 0,
  startY: 521,
  partW: 24,
  partH: 74
};

chute_heart_tile = {
  x: 1,
  y: 1,
  w: 63,
  h: 74,
  startX: 25,
  startY: 521,
  partW: 63,
  partH: 74
};

chute_hippie_tile = {
  x: 1,
  y: 1,
  w: 64,
  h: 64,
  startX: 89,
  startY: 521,
  partW: 64,
  partH: 64
};

chute_anar_tile = {
  x: 1,
  y: 1,
  w: 73,
  h: 74,
  startX: 152,
  startY: 521,
  partW: 73,
  partH: 74
};

chute_coco_tile = {
  x: 1,
  y: 1,
  w: 70,
  h: 74,
  startX: 224,
  startY: 521,
  partW: 70,
  partH: 74
};

app = new App();

app.event = new Event();

app.startCycle(true);

app.fullScreenOn();

app.canvas = new Canvas(app, "canvas", 800, 600);

childhood = function() {
  return this;
};

childhood.start = function() {
  var _this = this;
  this.earth = new Node();
  this.earth.addSquare(0, 0, 0, 500);
  this.earth.addTexture(earth_tile, app.decor);
  this.earth.animateTexture(5, 0, 1, -1);
  this.sky = new Node();
  this.sky.addSquare(0, 0, 0, 0);
  this.sky.addTexture(sky_tile, app.decor);
  this.sky.animateTexture(2, 0, 1, -1);
  this.btree = new Node();
  this.btree.addSquare(0, 0, 0, 175);
  this.btree.addTexture(big_tree_tile, app.decor);
  this.btree.animateTexture(3, 0, 1, -1);
  this.ltree = new Node();
  this.ltree.addSquare(0, 0, 0, 353);
  this.ltree.addTexture(little_tree_tile, app.decor);
  this.ltree.animateTexture(4, 0, 1, -1);
  this.sky.drawTexture(null, null, app.canvas);
  this.btree.drawTexture(null, null, app.canvas);
  this.ltree.drawTexture(null, null, app.canvas);
  this.earth.drawTexture(null, null, app.canvas);
  this.col = new Collection();
  return this.col._spawn = this.col.addCycle(100, -1, function() {
    var node;
    node = new Node();
    node.addSquare(22, 27, 800, 250 + Math.floor(Math.random() * 250));
    node.addTile(butterfly_tile, app.img);
    node.animateTile(0, 1, false, 4, -1);
    node.drawTile(null, null, app.canvas);
    return _this.col.add(node);
  });
};

childhood.childArrive = function() {
  var _this = this;
  this.child = new Node();
  this.child.addSquare(50, 50, -10, -110);
  this.child.addTile(child_tile, app.img);
  this.child.animateTile(0, 6, false, 4, -1);
  this.child.slideTo(100, 450, 20, function() {
    _this.child._jumpYGravity = 1;
    return _this.child._jump = pubsub.subscribe("up", function() {
      return _this.child.animateTile(7, 11, true, 4, -1).jumpY(-20, _this.child._jumpYGravity, function() {
        return _this.child.animateTile(0, 6, false, 4, -1);
      });
    });
  });
  this.child.drawTile(null, null, app.canvas);
  return this.col._move = this.col.addCycle(1, -1, function() {
    _this.col.each(function(elem) {
      elem.move(-2, 0);
      if (elem.square.xx <= 0) {
        return elem.killTile();
      }
    });
    if (_this.child) {
      return _this.col.squareCollision(_this.child.square, function(elem) {
        return elem.killTile();
      });
    }
  });
};

childhood.cosmos = function() {
  var _this = this;
  app.canvas.clearEachFrame();
  this.btree.slideTo(800, 800, 30);
  this.ltree.slideTo(0, -500, 30);
  this.earth.slideTo(0, 800, 30);
  return this.sky.slideTo(0, -800, 35, function() {
    _this.sky.addTexture(sky_tile, app.decorSpace);
    _this.btree.addTexture(big_tree_tile, app.decorSpace);
    _this.ltree.addTexture(little_tree_tile, app.decorSpace);
    _this.ltree.animateTexture(4, 0, 1, -1);
    _this.sky.animateTexture(2, 0, 1, -1);
    _this.btree.animateTexture(3, 0, 1, -1);
    _this.earth.addTexture(moon_tile, app.decorSpace);
    _this.earth.animateTexture(5, 0, 1, -1);
    return _this.sky.slideTo(0, 0, 40, function() {
      return _this.earth.slideTo(0, 500, 40, function() {
        return _this.btree.slideTo(0, 175, 40, function() {
          return _this.ltree.slideTo(0, 353, 40, function() {
            _this.spuf = new Node();
            _this.spuf.addSquare(120, 120, 120, 120);
            _this.spuf.addTile(spuf_tile, app.spuf);
            _this.spuf.drawTile(null, null, app.canvas);
            _this.spuf.follow(_this.child, 0, 20);
            _this.spuf.animateTile(0, 5, true, 2, 6, (function() {
              return _this.spuf.kill();
            }));
            _this.child.addTile(cosmos_tile, app.img);
            _this.child._jumpYGravity = 0.5;
            _this.col.killCycle(_this.col._move);
            _this.col.killCycle(_this.col._spawn);
            return _this.col.killAll();
          });
        });
      });
    });
  });
};

childhood.veto = function() {
  var _this = this;
  this.btree.slideTo(800, 800, 30);
  this.ltree.slideTo(0, -500, 30);
  this.earth.slideTo(0, 800, 30);
  return this.sky.slideTo(0, -800, 35, function() {
    _this.sky.addTexture(sky_tile, app.decorVeto);
    _this.btree.addTexture(big_tree_tile, app.decorVeto);
    _this.ltree.addTexture(cat_veto_tile, app.decorVeto);
    _this.ltree.animateTexture(4, 0, 1, -1);
    _this.sky.animateTexture(2, 0, 1, -1);
    _this.btree.animateTexture(3, 0, 1, -1);
    _this.earth.addTexture(earth_tile, app.decorVeto);
    _this.earth.animateTexture(5, 0, 1, -1);
    return _this.sky.slideTo(0, 0, 40, function() {
      return _this.earth.slideTo(0, 500, 40, function() {
        return _this.btree.slideTo(0, 175, 40, function() {
          return _this.ltree.slideTo(0, 50, 40, function() {
            _this.spuf = new Node();
            _this.spuf.addSquare(120, 120, 120, 120);
            _this.spuf.addTile(spuf_tile, app.spuf);
            _this.spuf.drawTile(null, null, app.canvas);
            _this.spuf.follow(_this.child, 2, 0, 20);
            _this.spuf.animateTile(0, 5, true, 2, 6, function() {
              return _this.spuf.kill();
            });
            _this.child.addTile(veto_tile, app.img);
            _this.child._jumpYGravity = 1;
            return app.canvas.stopClearEachFrame();
          });
        });
      });
    });
  });
};

childhood.childBack = function() {
  var _this = this;
  this.spuf = new Node();
  this.spuf.addSquare(120, 120, 120, 120);
  this.spuf.addTile(spuf_tile, app.spuf);
  this.spuf.drawTile(null, null, app.canvas);
  this.spuf.follow(this.child, 2, 0, 20);
  this.spuf.animateTile(0, 5, true, 2, 6, function() {
    return _this.spuf.kill();
  });
  return this.child.addTile(child_tile, app.img);
};

childhood.earthquake = function() {
  var _this = this;
  this.sky.stopAnimateTexture();
  this.btree.stopAnimateTexture();
  this.ltree.stopAnimateTexture();
  this.earth.stopAnimateTexture();
  pubsub.unsubscribe(this.child._jump);
  this.sky.shake(4, 30);
  this.earth.shake(5, 30);
  this.ltree.shake(10, 30);
  this.btree.shake(10, 30);
  return this.child.slideTo(400, 450, 50, function() {
    _this.child.addTile(child_tile, app.img);
    _this.child.animateTile(4, 4, false, 4, 1);
    _this.child.stopAnimateTile();
    return _this.child.shake(5, 30);
  });
};

childhood.stop = function() {
  this.sky.killAll();
  this.btree.killAll();
  this.ltree.killAll();
  this.earth.killAll();
  return this.child.killAll();
};

chute = function() {
  return this;
};

chute.start = function() {
  var _this = this;
  this.sky = new Node();
  this.sky.addSquare(0, 0, 0, 0);
  this.sky.addTexture(chute_sky_tile, app.decorChute);
  this.sky.animateTexture(0, 9, 1, -1);
  this.sky.drawTexture(null, null, app.canvas);
  this.leftWall = new Node();
  this.leftWall.addSquare(0, 0, 0, 0);
  this.leftWall.addTexture(chute_wall_tile, app.decorChute);
  this.leftWall.animateTexture(0, 12, 1, -1);
  this.leftWall.drawTexture(null, null, app.canvas);
  this.rightWall = new Node();
  this.rightWall.addSquare(0, 0, 800 - 78, 0);
  this.rightWall.addTexture(chute_wall_tile, app.decorChute);
  this.rightWall.animateTexture(0, 12, 1, -1);
  this.rightWall.drawTexture(null, null, app.canvas);
  this.me = new Node();
  this.me.addSquare(111, 132, 300, -140);
  this.me.addTile(chute_me_tile, app.decorChute);
  this.me.animateTile(0, 5, true, 4, -1);
  this.me.slideTo(300, 300, 40, function() {
    return _this.me.square.startFreeMove(app.event, -2, 2, 2, -2, 0, 800 - 78, 600, 78);
  });
  return this.me.drawTile(null, null, app.canvas);
};

chute.love = function() {
  var _this = this;
  this.col = new Collection();
  this.col._addNode = function() {
    var node;
    node = new Node();
    node.addSquare(67, 74, 78 + Math.floor(Math.random() * 600), 650);
    node.addTile(chute_heart_tile, app.decorChute);
    node.drawTile(null, null, app.canvas);
    return node;
  };
  this.col._spawn = this.col.addCycle(30, -1, function() {
    var node;
    node = _this.col._addNode();
    return _this.col.add(node);
  });
  return this.col._move = this.col.addCycle(1, -1, function() {
    _this.col.each(function(elem) {
      elem.move(0, -3);
      if (elem.square.yy <= 0) {
        return elem.killTile();
      }
    });
    if (_this.me) {
      return _this.col.squareCollision(_this.me.square, function(elem) {
        return elem.killTile();
      });
    }
  });
};

chute.beer = function() {
  return this.col._addNode = function() {
    var node;
    node = new Node();
    node.addSquare(24, 74, 78 + Math.floor(Math.random() * 600), 650);
    node.addTile(chute_bottle_tile, app.decorChute);
    node.drawTile(null, null, app.canvas);
    return node;
  };
};

chute.hippie = function() {
  return this.col._addNode = function() {
    var node;
    node = new Node();
    node.addSquare(64, 64, 78 + Math.floor(Math.random() * 600), 650);
    node.addTile(chute_hippie_tile, app.decorChute);
    node.drawTile(null, null, app.canvas);
    return node;
  };
};

chute.anar = function() {
  return this.col._addNode = function() {
    var node;
    node = new Node();
    node.addSquare(73, 74, 78 + Math.floor(Math.random() * 600), 650);
    node.addTile(chute_anar_tile, app.decorChute);
    node.drawTile(null, null, app.canvas);
    return node;
  };
};

chute.coco = function() {
  return this.col._addNode = function() {
    var node;
    node = new Node();
    node.addSquare(73, 74, 78 + Math.floor(Math.random() * 600), 650);
    node.addTile(chute_coco_tile, app.decorChute);
    node.drawTile(null, null, app.canvas);
    return node;
  };
};

chute.stopCol = function() {
  this.col.killCycle(this.col._move);
  this.col.killCycle(this.col._spawn);
  return this.col.killAll();
};

chute.end = function() {
  this.sky.killAll();
  this.leftWall.killAll();
  this.rightWall.killAll();
  return this.me.killAll();
};

end = function() {
  app.canvas.stopClearEachFrame();
  chute.end();
  return app.stopCycle();
};

text = [
  {
    exec: function() {
      return childhood.start();
    },
    print: true,
    sleep: 250,
    tmpSleep: 25,
    txt: "CV César LEBLIC\n2012",
    x: 400,
    y: 300,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "60"
  }, {
    exec: function() {
      return childhood.childArrive();
    },
    print: false,
    sleep: 100,
    tmpSleep: 10
  }, {
    exec: false,
    print: true,
    sleep: 200,
    tmpSleep: 20,
    txt: "Mon enfance fût tranquille",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: false,
    print: true,
    sleep: 200,
    tmpSleep: 20,
    txt: "comme tout les enfants,\n je revais à de bien beaux métiers.",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: function() {
      return childhood.cosmos();
    },
    print: true,
    sleep: 400,
    tmpSleep: 40,
    txt: "J'ai voulu être cosmonaute",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: false,
    print: true,
    sleep: 150,
    tmpSleep: 15,
    txt: "ainsi que...",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: function() {
      return childhood.veto();
    },
    print: true,
    sleep: 400,
    tmpSleep: 40,
    txt: "vétérinaire",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: function() {
      return childhood.childBack();
    },
    print: false,
    sleep: 150,
    tmpSleep: 40,
    txt: "",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: false,
    print: true,
    sleep: 400,
    tmpSleep: 40,
    txt: "puis\nalors que je ne m'y attendais pas\narriva...",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: function() {
      return childhood.earthquake();
    },
    print: true,
    sleep: 210,
    tmpSleep: 400,
    txt: "L'ADOLESCENCE",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "70"
  }, {
    exec: function() {
      childhood.stop();
      return chute.start();
    },
    print: true,
    sleep: 120,
    tmpSleep: 400,
    txt: "L'ADOLESCENCE",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "70"
  }, {
    exec: false,
    print: true,
    sleep: 180,
    tmpSleep: 400,
    txt: "Je fais ma scolarité au collège Condorcet\npuis au lycée Racine",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: false,
    print: true,
    sleep: 180,
    tmpSleep: 400,
    txt: "Je participe à la création de Prométhée:\nqui reçoit le prix\ndu meilleur journal lycéen\nen 2005",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: false,
    print: true,
    sleep: 160,
    tmpSleep: 400,
    txt: "A part ça\nrien de très interessant à raconter...",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: function() {
      return chute.love();
    },
    print: true,
    sleep: 300,
    tmpSleep: 400,
    txt: "J'y ai découvert l'amour ...",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: function() {
      return chute.beer();
    },
    print: true,
    sleep: 300,
    tmpSleep: 400,
    txt: "la bière ...",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: false,
    print: true,
    sleep: 180,
    tmpSleep: 400,
    txt: "J'ai été pas mal de chose...",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: function() {
      return chute.hippie();
    },
    print: true,
    sleep: 220,
    tmpSleep: 400,
    txt: "un jour hippie...",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: function() {
      return chute.anar();
    },
    print: true,
    sleep: 180,
    tmpSleep: 400,
    txt: "un autre anarchiste...",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: function() {
      return chute.coco();
    },
    print: true,
    sleep: 180,
    tmpSleep: 400,
    txt: "un autre communiste...",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: function() {
      return chute.stopCol();
    },
    print: true,
    sleep: 80,
    tmpSleep: 400,
    txt: "BREF",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "70"
  }, {
    exec: false,
    print: true,
    sleep: 180,
    tmpSleep: 400,
    txt: "C'était l'adolescence",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: false,
    print: true,
    sleep: 110,
    tmpSleep: 400,
    txt: "Puis arriva...",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: false,
    print: true,
    sleep: 110,
    tmpSleep: 400,
    txt: "FIN !!!\n:D",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "70"
  }, {
    exec: false,
    print: true,
    sleep: 330,
    tmpSleep: 400,
    txt: "Je m'arrête là pour le moment,\ncar mine de rien\n ca prend du temps de dessiner\nces petites sprites\naussi moches soient-elles héhé",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: false,
    print: true,
    sleep: 110,
    tmpSleep: 400,
    txt: "Suite prochainement",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }, {
    exec: function() {
      return end();
    },
    print: false,
    sleep: 110,
    tmpSleep: 400,
    txt: "",
    x: 400,
    y: 80,
    bgColor: "#fff",
    txtColor: "#000",
    fontFamily: "Changa One",
    fontSize: "40"
  }
];

app.loadImages([
  {
    name: "img",
    src: "img/child.png"
  }, {
    name: "decor",
    src: "img/decor-child.png"
  }, {
    name: "spuf",
    src: "img/spuf.png"
  }, {
    name: "decorSpace",
    src: "img/decor-space.png"
  }, {
    name: "decorVeto",
    src: "img/decor-veto.png"
  }, {
    name: "decorChute",
    src: "img/decor-chute.png"
  }
], function() {
  var reader;
  reader = new Reader(text, app.canvas);
  return reader.read();
});
